# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AxisDriver

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EthernetPortMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EthernetPortMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEthernetPortMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EthernetPortMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EthernetPortMessage
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def EthernetPortMessageStart(builder):
    builder.StartObject(1)

def Start(builder):
    EthernetPortMessageStart(builder)

def EthernetPortMessageAddValue(builder, value):
    builder.PrependUint32Slot(0, value, 0)

def AddValue(builder, value):
    EthernetPortMessageAddValue(builder, value)

def EthernetPortMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return EthernetPortMessageEnd(builder)
