# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AxisDriver

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HAIpAddressMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HAIpAddressMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHAIpAddressMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HAIpAddressMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HAIpAddressMessage
    def HaIpAddress(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def HAIpAddressMessageStart(builder):
    builder.StartObject(1)

def Start(builder):
    HAIpAddressMessageStart(builder)

def HAIpAddressMessageAddHaIpAddress(builder, haIpAddress):
    builder.PrependUint32Slot(0, haIpAddress, 0)

def AddHaIpAddress(builder, haIpAddress):
    HAIpAddressMessageAddHaIpAddress(builder, haIpAddress)

def HAIpAddressMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return HAIpAddressMessageEnd(builder)
