# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AxisDriver

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HAMqttIconMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HAMqttIconMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHAMqttIconMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HAMqttIconMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HAMqttIconMessage
    def Value(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # HAMqttIconMessage
    def ValueAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # HAMqttIconMessage
    def ValueLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HAMqttIconMessage
    def ValueIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def HAMqttIconMessageStart(builder):
    builder.StartObject(1)

def Start(builder):
    HAMqttIconMessageStart(builder)

def HAMqttIconMessageAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    HAMqttIconMessageAddValue(builder, value)

def HAMqttIconMessageStartValueVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartValueVector(builder, numElems):
    return HAMqttIconMessageStartValueVector(builder, numElems)

def HAMqttIconMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return HAMqttIconMessageEnd(builder)
