# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AxisDriver

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HAMqttUserMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HAMqttUserMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHAMqttUserMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HAMqttUserMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HAMqttUserMessage
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def HAMqttUserMessageStart(builder):
    builder.StartObject(1)

def Start(builder):
    HAMqttUserMessageStart(builder)

def HAMqttUserMessageAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    HAMqttUserMessageAddValue(builder, value)

def HAMqttUserMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return HAMqttUserMessageEnd(builder)
