# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AxisDriver

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HAMqttNameMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HAMqttNameMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHAMqttNameMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HAMqttNameMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HAMqttNameMessage
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def HAMqttNameMessageStart(builder):
    builder.StartObject(1)

def Start(builder):
    HAMqttNameMessageStart(builder)

def HAMqttNameMessageAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    HAMqttNameMessageAddValue(builder, value)

def HAMqttNameMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return HAMqttNameMessageEnd(builder)
