# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AxisDriver

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HAVelocitySwitchOffSpeedMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HAVelocitySwitchOffSpeedMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHAVelocitySwitchOffSpeedMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HAVelocitySwitchOffSpeedMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HAVelocitySwitchOffSpeedMessage
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def HAVelocitySwitchOffSpeedMessageStart(builder):
    builder.StartObject(1)

def Start(builder):
    HAVelocitySwitchOffSpeedMessageStart(builder)

def HAVelocitySwitchOffSpeedMessageAddValue(builder, value):
    builder.PrependFloat32Slot(0, value, 0.0)

def AddValue(builder, value):
    HAVelocitySwitchOffSpeedMessageAddValue(builder, value)

def HAVelocitySwitchOffSpeedMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return HAVelocitySwitchOffSpeedMessageEnd(builder)
