# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AxisDriver

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HAVelocitySliderMaxMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HAVelocitySliderMaxMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHAVelocitySliderMaxMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HAVelocitySliderMaxMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HAVelocitySliderMaxMessage
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def HAVelocitySliderMaxMessageStart(builder):
    builder.StartObject(1)

def Start(builder):
    HAVelocitySliderMaxMessageStart(builder)

def HAVelocitySliderMaxMessageAddValue(builder, value):
    builder.PrependFloat32Slot(0, value, 0.0)

def AddValue(builder, value):
    HAVelocitySliderMaxMessageAddValue(builder, value)

def HAVelocitySliderMaxMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return HAVelocitySliderMaxMessageEnd(builder)
