# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AxisDriver

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HomeThresholdMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HomeThresholdMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHomeThresholdMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HomeThresholdMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HomeThresholdMessage
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def HomeThresholdMessageStart(builder):
    builder.StartObject(1)

def Start(builder):
    HomeThresholdMessageStart(builder)

def HomeThresholdMessageAddValue(builder, value):
    builder.PrependUint32Slot(0, value, 0)

def AddValue(builder, value):
    HomeThresholdMessageAddValue(builder, value)

def HomeThresholdMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return HomeThresholdMessageEnd(builder)
