# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AxisDriver

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HomeDirectionMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HomeDirectionMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHomeDirectionMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HomeDirectionMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HomeDirectionMessage
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def HomeDirectionMessageStart(builder):
    builder.StartObject(1)

def Start(builder):
    HomeDirectionMessageStart(builder)

def HomeDirectionMessageAddValue(builder, value):
    builder.PrependInt8Slot(0, value, 0)

def AddValue(builder, value):
    HomeDirectionMessageAddValue(builder, value)

def HomeDirectionMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return HomeDirectionMessageEnd(builder)
