# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AxisDriver

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class I2CAddressMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = I2CAddressMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsI2CAddressMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # I2CAddressMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # I2CAddressMessage
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def I2CAddressMessageStart(builder):
    builder.StartObject(1)

def Start(builder):
    I2CAddressMessageStart(builder)

def I2CAddressMessageAddValue(builder, value):
    builder.PrependUint8Slot(0, value, 0)

def AddValue(builder, value):
    I2CAddressMessageAddValue(builder, value)

def I2CAddressMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return I2CAddressMessageEnd(builder)
