# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AxisDriver

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LedColorMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LedColorMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLedColorMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LedColorMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LedColorMessage
    def LedColor(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # LedColorMessage
    def LedColorAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # LedColorMessage
    def LedColorLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LedColorMessage
    def LedColorIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def LedColorMessageStart(builder):
    builder.StartObject(1)

def Start(builder):
    LedColorMessageStart(builder)

def LedColorMessageAddLedColor(builder, ledColor):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(ledColor), 0)

def AddLedColor(builder, ledColor):
    LedColorMessageAddLedColor(builder, ledColor)

def LedColorMessageStartLedColorVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartLedColorVector(builder, numElems):
    return LedColorMessageStartLedColorVector(builder, numElems)

def LedColorMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return LedColorMessageEnd(builder)
