# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AxisDriver

class LedStates(object):
    OFF = 0
    FLASH_ERROR = 1
    ERROR = 2
    BOOTUP = 3
    RAINBOW = 4
    SOLID = 5
    MAX_VALUE = 6
