# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AxisDriver

class MotorStates(object):
    OFF = 0
    POSITION = 1
    VELOCITY = 2
    VELOCITY_STEP = 3
    IDLE_ON = 4
    HOME = 5
