# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AxisDriver

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SaveConfigurationMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SaveConfigurationMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSaveConfigurationMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SaveConfigurationMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SaveConfigurationMessage
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def SaveConfigurationMessageStart(builder):
    builder.StartObject(1)

def Start(builder):
    SaveConfigurationMessageStart(builder)

def SaveConfigurationMessageAddValue(builder, value):
    builder.PrependUint8Slot(0, value, 0)

def AddValue(builder, value):
    SaveConfigurationMessageAddValue(builder, value)

def SaveConfigurationMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return SaveConfigurationMessageEnd(builder)
