# automatically generated by the FlatBuffers compiler, do not modify

# namespace: AxisDriver

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VelocityMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VelocityMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVelocityMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VelocityMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VelocityMessage
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def VelocityMessageStart(builder):
    builder.StartObject(1)

def Start(builder):
    VelocityMessageStart(builder)

def VelocityMessageAddValue(builder, value):
    builder.PrependFloat32Slot(0, value, 0.0)

def AddValue(builder, value):
    VelocityMessageAddValue(builder, value)

def VelocityMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return VelocityMessageEnd(builder)
