import time
import DriverComms
import Messages
import Serial

SerialComms = Serial.AxisSerial('/dev/ttyACM0')


print("Flashing Error")
msg = DriverComms.SetU8(Messages.MessageTypes.SetLedState, 1)
SerialComms.send_message(msg)
time.sleep(2)
print("Setting LED state to solid")
msg = DriverComms.SetU8(Messages.MessageTypes.SetLedState, 5)
SerialComms.send_message(msg)
print("Setting LED color to blue")
msg = DriverComms.SetLedColor(Messages.MessageTypes.SetLedColor, 0, 0, 255)
SerialComms.send_message(msg)
time.sleep(2)
print("Setting LED color to green")
msg = DriverComms.SetLedColor(Messages.MessageTypes.SetLedColor, 0, 255, 0)
SerialComms.send_message(msg)
time.sleep(2)
print("Setting LED color to red")
msg = DriverComms.SetLedColor(Messages.MessageTypes.SetLedColor, 255, 0, 0)
SerialComms.send_message(msg)
time.sleep(2)
print("Setting LED color to white")
msg = DriverComms.SetLedColor(Messages.MessageTypes.SetLedColor, 251, 253, 255)
SerialComms.send_message(msg)
time.sleep(1)
msg = DriverComms.SetLedColor(Messages.MessageTypes.GetLedColor, 0, 0, 0)
SerialComms.send_message(msg)
ret = SerialComms.wait_serial_message()
print("Received LED color: R: {}, G: {}, B: {}".format(ret[4], ret[5], ret[6]))
time.sleep(1)
print("Setting LED state to off")
msg = DriverComms.SetU8(Messages.MessageTypes.SetLedState, 0)
SerialComms.send_message(msg)
time.sleep(1)