import time
import Comms

print("Flashing Error")
Comms.SetU8(Comms.MessageTypes.SetLedState, 1)
time.sleep(2)
print("Setting LED state to solid")
Comms.SetU8(Comms.MessageTypes.SetLedState, 5)
print("Setting LED color to blue")
Comms.SetLedColor(Comms.MessageTypes.SetLedColor, 0, 0, 255)
time.sleep(2)
print("Setting LED color to green")
Comms.SetLedColor(Comms.MessageTypes.SetLedColor, 0, 255, 0)
time.sleep(2)
print("Setting LED color to red")
Comms.SetLedColor(Comms.MessageTypes.SetLedColor, 255, 0, 0)
time.sleep(2)
print("Setting LED color to white")
Comms.SetLedColor(Comms.MessageTypes.SetLedColor, 251, 253, 255)
time.sleep(1)
ret = Comms.GetLedColor(Comms.MessageTypes.GetLedColor)
print("Received LED color: R: {}, G: {}, B: {}".format(ret[4], ret[5], ret[6]))
time.sleep(1)
print("Setting LED state to off")
Comms.SetU8(Comms.MessageTypes.SetLedState, 0)
time.sleep(1)