# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AxisMessages_motor.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'AxisMessages_motor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x41xisMessages_motor.proto\x12\nAxisDriver\"%\n\x14HomeDirectionMessage\x12\r\n\x05value\x18\x01 \x01(\x05\"!\n\x10HomeSpeedMessage\x12\r\n\x05value\x18\x01 \x01(\r\"%\n\x14HomeThresholdMessage\x12\r\n\x05value\x18\x01 \x01(\r\"\"\n\x11HomedStateMessage\x12\r\n\x05value\x18\x01 \x01(\x08\"\x1c\n\x0bHomeMessage\x12\r\n\x05value\x18\x01 \x01(\r\"\"\n\x11MotorStateMessage\x12\r\n\x05value\x18\x01 \x01(\r\"\"\n\x11MotorBrakeMessage\x12\r\n\x05value\x18\x01 \x01(\r\" \n\x0fMaxSpeedMessage\x12\r\n\x05value\x18\x01 \x01(\r\"$\n\x13\x41\x63\x63\x65lerationMessage\x12\r\n\x05value\x18\x01 \x01(\r\"\'\n\x16\x43urrentPositionMessage\x12\r\n\x05value\x18\x01 \x01(\x02\"&\n\x15TargetPositionMessage\x12\r\n\x05value\x18\x01 \x01(\x02\".\n\x1dRelativeTargetPositionMessage\x12\r\n\x05value\x18\x01 \x01(\x02\" \n\x0fVelocityMessage\x12\r\n\x05value\x18\x01 \x01(\x02\"Q\n\x17VelocityAndStepsMessage\x12\x10\n\x08velocity\x18\x01 \x01(\x05\x12\r\n\x05steps\x18\x02 \x01(\x05\x12\x15\n\rposition_mode\x18\x03 \x01(\r\"!\n\x10StartPathMessage\x12\r\n\x05value\x18\x01 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AxisMessages_motor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HOMEDIRECTIONMESSAGE']._serialized_start=40
  _globals['_HOMEDIRECTIONMESSAGE']._serialized_end=77
  _globals['_HOMESPEEDMESSAGE']._serialized_start=79
  _globals['_HOMESPEEDMESSAGE']._serialized_end=112
  _globals['_HOMETHRESHOLDMESSAGE']._serialized_start=114
  _globals['_HOMETHRESHOLDMESSAGE']._serialized_end=151
  _globals['_HOMEDSTATEMESSAGE']._serialized_start=153
  _globals['_HOMEDSTATEMESSAGE']._serialized_end=187
  _globals['_HOMEMESSAGE']._serialized_start=189
  _globals['_HOMEMESSAGE']._serialized_end=217
  _globals['_MOTORSTATEMESSAGE']._serialized_start=219
  _globals['_MOTORSTATEMESSAGE']._serialized_end=253
  _globals['_MOTORBRAKEMESSAGE']._serialized_start=255
  _globals['_MOTORBRAKEMESSAGE']._serialized_end=289
  _globals['_MAXSPEEDMESSAGE']._serialized_start=291
  _globals['_MAXSPEEDMESSAGE']._serialized_end=323
  _globals['_ACCELERATIONMESSAGE']._serialized_start=325
  _globals['_ACCELERATIONMESSAGE']._serialized_end=361
  _globals['_CURRENTPOSITIONMESSAGE']._serialized_start=363
  _globals['_CURRENTPOSITIONMESSAGE']._serialized_end=402
  _globals['_TARGETPOSITIONMESSAGE']._serialized_start=404
  _globals['_TARGETPOSITIONMESSAGE']._serialized_end=442
  _globals['_RELATIVETARGETPOSITIONMESSAGE']._serialized_start=444
  _globals['_RELATIVETARGETPOSITIONMESSAGE']._serialized_end=490
  _globals['_VELOCITYMESSAGE']._serialized_start=492
  _globals['_VELOCITYMESSAGE']._serialized_end=524
  _globals['_VELOCITYANDSTEPSMESSAGE']._serialized_start=526
  _globals['_VELOCITYANDSTEPSMESSAGE']._serialized_end=607
  _globals['_STARTPATHMESSAGE']._serialized_start=609
  _globals['_STARTPATHMESSAGE']._serialized_end=642
# @@protoc_insertion_point(module_scope)
