# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AxisMessages_ha.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'AxisMessages_ha.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x41xisMessages_ha.proto\x12\nAxisDriver\" \n\x0fHAEnableMessage\x12\r\n\x05value\x18\x01 \x01(\r\"\x1e\n\rHAModeMessage\x12\r\n\x05value\x18\x01 \x01(\r\"+\n\x12HAIpAddressMessage\x12\x15\n\rha_ip_address\x18\x01 \x01(\r\"/\n\x1eHAVelocitySwitchOnSpeedMessage\x12\r\n\x05value\x18\x01 \x01(\x02\"0\n\x1fHAVelocitySwitchOffSpeedMessage\x12\r\n\x05value\x18\x01 \x01(\x02\"2\n!HAPositionSwitchOnPositionMessage\x12\r\n\x05value\x18\x01 \x01(\x02\"3\n\"HAPositionSwitchOffPositionMessage\x12\r\n\x05value\x18\x01 \x01(\x02\"+\n\x1aHAVelocitySliderMinMessage\x12\r\n\x05value\x18\x01 \x01(\x02\"+\n\x1aHAVelocitySliderMaxMessage\x12\r\n\x05value\x18\x01 \x01(\x02\"+\n\x1aHAPositionSliderMinMessage\x12\r\n\x05value\x18\x01 \x01(\x02\"+\n\x1aHAPositionSliderMaxMessage\x12\r\n\x05value\x18\x01 \x01(\x02\"\"\n\x11HAMqttUserMessage\x12\r\n\x05value\x18\x01 \x01(\t\"&\n\x15HAMqttPasswordMessage\x12\r\n\x05value\x18\x01 \x01(\t\"\"\n\x11HAMqttNameMessage\x12\r\n\x05value\x18\x01 \x01(\t\"\"\n\x11HAMqttIconMessage\x12\r\n\x05value\x18\x01 \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AxisMessages_ha_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HAENABLEMESSAGE']._serialized_start=37
  _globals['_HAENABLEMESSAGE']._serialized_end=69
  _globals['_HAMODEMESSAGE']._serialized_start=71
  _globals['_HAMODEMESSAGE']._serialized_end=101
  _globals['_HAIPADDRESSMESSAGE']._serialized_start=103
  _globals['_HAIPADDRESSMESSAGE']._serialized_end=146
  _globals['_HAVELOCITYSWITCHONSPEEDMESSAGE']._serialized_start=148
  _globals['_HAVELOCITYSWITCHONSPEEDMESSAGE']._serialized_end=195
  _globals['_HAVELOCITYSWITCHOFFSPEEDMESSAGE']._serialized_start=197
  _globals['_HAVELOCITYSWITCHOFFSPEEDMESSAGE']._serialized_end=245
  _globals['_HAPOSITIONSWITCHONPOSITIONMESSAGE']._serialized_start=247
  _globals['_HAPOSITIONSWITCHONPOSITIONMESSAGE']._serialized_end=297
  _globals['_HAPOSITIONSWITCHOFFPOSITIONMESSAGE']._serialized_start=299
  _globals['_HAPOSITIONSWITCHOFFPOSITIONMESSAGE']._serialized_end=350
  _globals['_HAVELOCITYSLIDERMINMESSAGE']._serialized_start=352
  _globals['_HAVELOCITYSLIDERMINMESSAGE']._serialized_end=395
  _globals['_HAVELOCITYSLIDERMAXMESSAGE']._serialized_start=397
  _globals['_HAVELOCITYSLIDERMAXMESSAGE']._serialized_end=440
  _globals['_HAPOSITIONSLIDERMINMESSAGE']._serialized_start=442
  _globals['_HAPOSITIONSLIDERMINMESSAGE']._serialized_end=485
  _globals['_HAPOSITIONSLIDERMAXMESSAGE']._serialized_start=487
  _globals['_HAPOSITIONSLIDERMAXMESSAGE']._serialized_end=530
  _globals['_HAMQTTUSERMESSAGE']._serialized_start=532
  _globals['_HAMQTTUSERMESSAGE']._serialized_end=566
  _globals['_HAMQTTPASSWORDMESSAGE']._serialized_start=568
  _globals['_HAMQTTPASSWORDMESSAGE']._serialized_end=606
  _globals['_HAMQTTNAMEMESSAGE']._serialized_start=608
  _globals['_HAMQTTNAMEMESSAGE']._serialized_end=642
  _globals['_HAMQTTICONMESSAGE']._serialized_start=644
  _globals['_HAMQTTICONMESSAGE']._serialized_end=678
# @@protoc_insertion_point(module_scope)
