# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AxisMessages_settings.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'AxisMessages_settings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x41xisMessages_settings.proto\x12\nAxisDriver\"\x1f\n\x0eVersionMessage\x12\r\n\x05value\x18\x01 \x01(\t\"\"\n\x11I2CAddressMessage\x12\r\n\x05value\x18\x01 \x01(\r\"\'\n\x16\x45thernetAddressMessage\x12\r\n\x05value\x18\x01 \x01(\r\"$\n\x13\x45thernetPortMessage\x12\r\n\x05value\x18\x01 \x01(\r\"(\n\x11MacAddressMessage\x12\x13\n\x0bmac_address\x18\x01 \x03(\r\")\n\x18SaveConfigurationMessage\x12\r\n\x05value\x18\x01 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AxisMessages_settings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERSIONMESSAGE']._serialized_start=43
  _globals['_VERSIONMESSAGE']._serialized_end=74
  _globals['_I2CADDRESSMESSAGE']._serialized_start=76
  _globals['_I2CADDRESSMESSAGE']._serialized_end=110
  _globals['_ETHERNETADDRESSMESSAGE']._serialized_start=112
  _globals['_ETHERNETADDRESSMESSAGE']._serialized_end=151
  _globals['_ETHERNETPORTMESSAGE']._serialized_start=153
  _globals['_ETHERNETPORTMESSAGE']._serialized_end=189
  _globals['_MACADDRESSMESSAGE']._serialized_start=191
  _globals['_MACADDRESSMESSAGE']._serialized_end=231
  _globals['_SAVECONFIGURATIONMESSAGE']._serialized_start=233
  _globals['_SAVECONFIGURATIONMESSAGE']._serialized_end=274
# @@protoc_insertion_point(module_scope)
