M48
; DRILL file {KiCad 7.0.6} date Thu Feb 29 20:21:01 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-29T20:21:01-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X165.595Y-103.61
X165.595Y-109.39
T2
X134.5Y-84.5
X134.5Y-115.5
X165.5Y-84.5
X165.5Y-115.5
T0
M30
