// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AxisMessages_led.proto
// Protobuf C++ Version: 6.30.2

#include "AxisMessages_led.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace AxisDriver {

inline constexpr LedStateMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        value_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR LedStateMessage::LedStateMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(LedStateMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LedStateMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LedStateMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LedStateMessageDefaultTypeInternal() {}
  union {
    LedStateMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LedStateMessageDefaultTypeInternal _LedStateMessage_default_instance_;

inline constexpr LedColorMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : led_color_{},
        _led_color_cached_byte_size_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LedColorMessage::LedColorMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(LedColorMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LedColorMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LedColorMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LedColorMessageDefaultTypeInternal() {}
  union {
    LedColorMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LedColorMessageDefaultTypeInternal _LedColorMessage_default_instance_;
}  // namespace AxisDriver
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_AxisMessages_5fled_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_AxisMessages_5fled_2eproto = nullptr;
const ::uint32_t
    TableStruct_AxisMessages_5fled_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::AxisDriver::LedStateMessage, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::AxisDriver::LedStateMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AxisDriver::LedStateMessage, _impl_.value_),
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::AxisDriver::LedColorMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AxisDriver::LedColorMessage, _impl_.led_color_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::AxisDriver::LedStateMessage)},
        {10, -1, -1, sizeof(::AxisDriver::LedColorMessage)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::AxisDriver::_LedStateMessage_default_instance_._instance,
    &::AxisDriver::_LedColorMessage_default_instance_._instance,
};
const char descriptor_table_protodef_AxisMessages_5fled_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\026AxisMessages_led.proto\022\nAxisDriver\" \n\017"
    "LedStateMessage\022\r\n\005value\030\001 \001(\r\"$\n\017LedCol"
    "orMessage\022\021\n\tled_color\030\001 \003(\rb\006proto3"
};
static ::absl::once_flag descriptor_table_AxisMessages_5fled_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_AxisMessages_5fled_2eproto = {
    false,
    false,
    116,
    descriptor_table_protodef_AxisMessages_5fled_2eproto,
    "AxisMessages_led.proto",
    &descriptor_table_AxisMessages_5fled_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_AxisMessages_5fled_2eproto::offsets,
    file_level_enum_descriptors_AxisMessages_5fled_2eproto,
    file_level_service_descriptors_AxisMessages_5fled_2eproto,
};
namespace AxisDriver {
// ===================================================================

class LedStateMessage::_Internal {
 public:
  using HasBits =
      decltype(std::declval<LedStateMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(LedStateMessage, _impl_._has_bits_);
};

LedStateMessage::LedStateMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, LedStateMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AxisDriver.LedStateMessage)
}
LedStateMessage::LedStateMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const LedStateMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, LedStateMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE LedStateMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void LedStateMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.value_ = {};
}
LedStateMessage::~LedStateMessage() {
  // @@protoc_insertion_point(destructor:AxisDriver.LedStateMessage)
  SharedDtor(*this);
}
inline void LedStateMessage::SharedDtor(MessageLite& self) {
  LedStateMessage& this_ = static_cast<LedStateMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL LedStateMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) LedStateMessage(arena);
}
constexpr auto LedStateMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(LedStateMessage),
                                            alignof(LedStateMessage));
}
constexpr auto LedStateMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_LedStateMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &LedStateMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<LedStateMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &LedStateMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<LedStateMessage>(), &LedStateMessage::ByteSizeLong,
              &LedStateMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(LedStateMessage, _impl_._cached_size_),
          false,
      },
      &LedStateMessage::kDescriptorMethods,
      &descriptor_table_AxisMessages_5fled_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull LedStateMessage_class_data_ =
        LedStateMessage::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL LedStateMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&LedStateMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(LedStateMessage_class_data_.tc_table);
  return LedStateMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
LedStateMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(LedStateMessage, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    LedStateMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AxisDriver::LedStateMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 value = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LedStateMessage, _impl_.value_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(LedStateMessage, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 value = 1;
    {PROTOBUF_FIELD_OFFSET(LedStateMessage, _impl_.value_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void LedStateMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:AxisDriver.LedStateMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL LedStateMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const LedStateMessage& this_ = static_cast<const LedStateMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL LedStateMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const LedStateMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:AxisDriver.LedStateMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 value = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_value() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_value(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AxisDriver.LedStateMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t LedStateMessage::ByteSizeLong(const MessageLite& base) {
  const LedStateMessage& this_ = static_cast<const LedStateMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t LedStateMessage::ByteSizeLong() const {
  const LedStateMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:AxisDriver.LedStateMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // uint32 value = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_value() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_value());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void LedStateMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LedStateMessage*>(&to_msg);
  auto& from = static_cast<const LedStateMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AxisDriver.LedStateMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_value() != 0) {
      _this->_impl_.value_ = from._impl_.value_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LedStateMessage::CopyFrom(const LedStateMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AxisDriver.LedStateMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LedStateMessage::InternalSwap(LedStateMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.value_, other->_impl_.value_);
}

::google::protobuf::Metadata LedStateMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class LedColorMessage::_Internal {
 public:
};

LedColorMessage::LedColorMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, LedColorMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AxisDriver.LedColorMessage)
}
PROTOBUF_NDEBUG_INLINE LedColorMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::AxisDriver::LedColorMessage& from_msg)
      : led_color_{visibility, arena, from.led_color_},
        _led_color_cached_byte_size_{0},
        _cached_size_{0} {}

LedColorMessage::LedColorMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const LedColorMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, LedColorMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  LedColorMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:AxisDriver.LedColorMessage)
}
PROTOBUF_NDEBUG_INLINE LedColorMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : led_color_{visibility, arena},
        _led_color_cached_byte_size_{0},
        _cached_size_{0} {}

inline void LedColorMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
LedColorMessage::~LedColorMessage() {
  // @@protoc_insertion_point(destructor:AxisDriver.LedColorMessage)
  SharedDtor(*this);
}
inline void LedColorMessage::SharedDtor(MessageLite& self) {
  LedColorMessage& this_ = static_cast<LedColorMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL LedColorMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) LedColorMessage(arena);
}
constexpr auto LedColorMessage::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(LedColorMessage, _impl_.led_color_) +
          decltype(LedColorMessage::_impl_.led_color_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(LedColorMessage), alignof(LedColorMessage), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&LedColorMessage::PlacementNew_,
                                 sizeof(LedColorMessage),
                                 alignof(LedColorMessage));
  }
}
constexpr auto LedColorMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_LedColorMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &LedColorMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<LedColorMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &LedColorMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<LedColorMessage>(), &LedColorMessage::ByteSizeLong,
              &LedColorMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(LedColorMessage, _impl_._cached_size_),
          false,
      },
      &LedColorMessage::kDescriptorMethods,
      &descriptor_table_AxisMessages_5fled_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull LedColorMessage_class_data_ =
        LedColorMessage::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL LedColorMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&LedColorMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(LedColorMessage_class_data_.tc_table);
  return LedColorMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
LedColorMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    LedColorMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AxisDriver::LedColorMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated uint32 led_color = 1;
    {::_pbi::TcParser::FastV32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(LedColorMessage, _impl_.led_color_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated uint32 led_color = 1;
    {PROTOBUF_FIELD_OFFSET(LedColorMessage, _impl_.led_color_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void LedColorMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:AxisDriver.LedColorMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.led_color_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL LedColorMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const LedColorMessage& this_ = static_cast<const LedColorMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL LedColorMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const LedColorMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:AxisDriver.LedColorMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated uint32 led_color = 1;
  {
    int byte_size = this_._impl_._led_color_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          1, this_._internal_led_color(), byte_size, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AxisDriver.LedColorMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t LedColorMessage::ByteSizeLong(const MessageLite& base) {
  const LedColorMessage& this_ = static_cast<const LedColorMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t LedColorMessage::ByteSizeLong() const {
  const LedColorMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:AxisDriver.LedColorMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated uint32 led_color = 1;
    {
      total_size +=
          ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
              this_._internal_led_color(), 1,
              this_._impl_._led_color_cached_byte_size_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void LedColorMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LedColorMessage*>(&to_msg);
  auto& from = static_cast<const LedColorMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AxisDriver.LedColorMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_led_color()->MergeFrom(from._internal_led_color());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LedColorMessage::CopyFrom(const LedColorMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AxisDriver.LedColorMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LedColorMessage::InternalSwap(LedColorMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.led_color_.InternalSwap(&other->_impl_.led_color_);
}

::google::protobuf::Metadata LedColorMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace AxisDriver
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_AxisMessages_5fled_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
