// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AxisMessages_settings.proto
// Protobuf C++ Version: 6.30.2

#include "AxisMessages_settings.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace AxisDriver {

inline constexpr VersionMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR VersionMessage::VersionMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(VersionMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct VersionMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VersionMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VersionMessageDefaultTypeInternal() {}
  union {
    VersionMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VersionMessageDefaultTypeInternal _VersionMessage_default_instance_;

inline constexpr SaveConfigurationMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        value_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR SaveConfigurationMessage::SaveConfigurationMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SaveConfigurationMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SaveConfigurationMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SaveConfigurationMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SaveConfigurationMessageDefaultTypeInternal() {}
  union {
    SaveConfigurationMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SaveConfigurationMessageDefaultTypeInternal _SaveConfigurationMessage_default_instance_;

inline constexpr MacAddressMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : mac_address_{},
        _mac_address_cached_byte_size_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MacAddressMessage::MacAddressMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MacAddressMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MacAddressMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MacAddressMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MacAddressMessageDefaultTypeInternal() {}
  union {
    MacAddressMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MacAddressMessageDefaultTypeInternal _MacAddressMessage_default_instance_;

inline constexpr I2CAddressMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        value_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR I2CAddressMessage::I2CAddressMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(I2CAddressMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct I2CAddressMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR I2CAddressMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~I2CAddressMessageDefaultTypeInternal() {}
  union {
    I2CAddressMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 I2CAddressMessageDefaultTypeInternal _I2CAddressMessage_default_instance_;

inline constexpr EthernetPortMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        value_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR EthernetPortMessage::EthernetPortMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(EthernetPortMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EthernetPortMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EthernetPortMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EthernetPortMessageDefaultTypeInternal() {}
  union {
    EthernetPortMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EthernetPortMessageDefaultTypeInternal _EthernetPortMessage_default_instance_;

inline constexpr EthernetAddressMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        value_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR EthernetAddressMessage::EthernetAddressMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(EthernetAddressMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EthernetAddressMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EthernetAddressMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EthernetAddressMessageDefaultTypeInternal() {}
  union {
    EthernetAddressMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EthernetAddressMessageDefaultTypeInternal _EthernetAddressMessage_default_instance_;
}  // namespace AxisDriver
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_AxisMessages_5fsettings_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_AxisMessages_5fsettings_2eproto = nullptr;
const ::uint32_t
    TableStruct_AxisMessages_5fsettings_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::AxisDriver::VersionMessage, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::AxisDriver::VersionMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AxisDriver::VersionMessage, _impl_.value_),
        0,
        PROTOBUF_FIELD_OFFSET(::AxisDriver::I2CAddressMessage, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::AxisDriver::I2CAddressMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AxisDriver::I2CAddressMessage, _impl_.value_),
        0,
        PROTOBUF_FIELD_OFFSET(::AxisDriver::EthernetAddressMessage, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::AxisDriver::EthernetAddressMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AxisDriver::EthernetAddressMessage, _impl_.value_),
        0,
        PROTOBUF_FIELD_OFFSET(::AxisDriver::EthernetPortMessage, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::AxisDriver::EthernetPortMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AxisDriver::EthernetPortMessage, _impl_.value_),
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::AxisDriver::MacAddressMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AxisDriver::MacAddressMessage, _impl_.mac_address_),
        PROTOBUF_FIELD_OFFSET(::AxisDriver::SaveConfigurationMessage, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::AxisDriver::SaveConfigurationMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AxisDriver::SaveConfigurationMessage, _impl_.value_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::AxisDriver::VersionMessage)},
        {10, 19, -1, sizeof(::AxisDriver::I2CAddressMessage)},
        {20, 29, -1, sizeof(::AxisDriver::EthernetAddressMessage)},
        {30, 39, -1, sizeof(::AxisDriver::EthernetPortMessage)},
        {40, -1, -1, sizeof(::AxisDriver::MacAddressMessage)},
        {49, 58, -1, sizeof(::AxisDriver::SaveConfigurationMessage)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::AxisDriver::_VersionMessage_default_instance_._instance,
    &::AxisDriver::_I2CAddressMessage_default_instance_._instance,
    &::AxisDriver::_EthernetAddressMessage_default_instance_._instance,
    &::AxisDriver::_EthernetPortMessage_default_instance_._instance,
    &::AxisDriver::_MacAddressMessage_default_instance_._instance,
    &::AxisDriver::_SaveConfigurationMessage_default_instance_._instance,
};
const char descriptor_table_protodef_AxisMessages_5fsettings_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\033AxisMessages_settings.proto\022\nAxisDrive"
    "r\"\037\n\016VersionMessage\022\r\n\005value\030\001 \001(\t\"\"\n\021I2"
    "CAddressMessage\022\r\n\005value\030\001 \001(\r\"\'\n\026Ethern"
    "etAddressMessage\022\r\n\005value\030\001 \001(\r\"$\n\023Ether"
    "netPortMessage\022\r\n\005value\030\001 \001(\r\"(\n\021MacAddr"
    "essMessage\022\023\n\013mac_address\030\001 \003(\r\")\n\030SaveC"
    "onfigurationMessage\022\r\n\005value\030\001 \001(\rb\006prot"
    "o3"
};
static ::absl::once_flag descriptor_table_AxisMessages_5fsettings_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_AxisMessages_5fsettings_2eproto = {
    false,
    false,
    282,
    descriptor_table_protodef_AxisMessages_5fsettings_2eproto,
    "AxisMessages_settings.proto",
    &descriptor_table_AxisMessages_5fsettings_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_AxisMessages_5fsettings_2eproto::offsets,
    file_level_enum_descriptors_AxisMessages_5fsettings_2eproto,
    file_level_service_descriptors_AxisMessages_5fsettings_2eproto,
};
namespace AxisDriver {
// ===================================================================

class VersionMessage::_Internal {
 public:
  using HasBits =
      decltype(std::declval<VersionMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(VersionMessage, _impl_._has_bits_);
};

VersionMessage::VersionMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, VersionMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AxisDriver.VersionMessage)
}
PROTOBUF_NDEBUG_INLINE VersionMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::AxisDriver::VersionMessage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        value_(arena, from.value_) {}

VersionMessage::VersionMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const VersionMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, VersionMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  VersionMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:AxisDriver.VersionMessage)
}
PROTOBUF_NDEBUG_INLINE VersionMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        value_(arena) {}

inline void VersionMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
VersionMessage::~VersionMessage() {
  // @@protoc_insertion_point(destructor:AxisDriver.VersionMessage)
  SharedDtor(*this);
}
inline void VersionMessage::SharedDtor(MessageLite& self) {
  VersionMessage& this_ = static_cast<VersionMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.value_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL VersionMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) VersionMessage(arena);
}
constexpr auto VersionMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(VersionMessage),
                                            alignof(VersionMessage));
}
constexpr auto VersionMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_VersionMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &VersionMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<VersionMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &VersionMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<VersionMessage>(), &VersionMessage::ByteSizeLong,
              &VersionMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(VersionMessage, _impl_._cached_size_),
          false,
      },
      &VersionMessage::kDescriptorMethods,
      &descriptor_table_AxisMessages_5fsettings_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull VersionMessage_class_data_ =
        VersionMessage::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL VersionMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VersionMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(VersionMessage_class_data_.tc_table);
  return VersionMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 39, 2>
VersionMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(VersionMessage, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    VersionMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AxisDriver::VersionMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string value = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(VersionMessage, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string value = 1;
    {PROTOBUF_FIELD_OFFSET(VersionMessage, _impl_.value_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\5\0\0\0\0\0\0"
    "AxisDriver.VersionMessage"
    "value"
  }},
};
PROTOBUF_NOINLINE void VersionMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:AxisDriver.VersionMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.value_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL VersionMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const VersionMessage& this_ = static_cast<const VersionMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL VersionMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const VersionMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:AxisDriver.VersionMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string value = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_value().empty()) {
      const std::string& _s = this_._internal_value();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "AxisDriver.VersionMessage.value");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AxisDriver.VersionMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t VersionMessage::ByteSizeLong(const MessageLite& base) {
  const VersionMessage& this_ = static_cast<const VersionMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t VersionMessage::ByteSizeLong() const {
  const VersionMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:AxisDriver.VersionMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string value = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_value().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_value());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void VersionMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<VersionMessage*>(&to_msg);
  auto& from = static_cast<const VersionMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AxisDriver.VersionMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!from._internal_value().empty()) {
      _this->_internal_set_value(from._internal_value());
    } else {
      if (_this->_impl_.value_.IsDefault()) {
        _this->_internal_set_value("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void VersionMessage::CopyFrom(const VersionMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AxisDriver.VersionMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void VersionMessage::InternalSwap(VersionMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
}

::google::protobuf::Metadata VersionMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class I2CAddressMessage::_Internal {
 public:
  using HasBits =
      decltype(std::declval<I2CAddressMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(I2CAddressMessage, _impl_._has_bits_);
};

I2CAddressMessage::I2CAddressMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, I2CAddressMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AxisDriver.I2CAddressMessage)
}
I2CAddressMessage::I2CAddressMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const I2CAddressMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, I2CAddressMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE I2CAddressMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void I2CAddressMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.value_ = {};
}
I2CAddressMessage::~I2CAddressMessage() {
  // @@protoc_insertion_point(destructor:AxisDriver.I2CAddressMessage)
  SharedDtor(*this);
}
inline void I2CAddressMessage::SharedDtor(MessageLite& self) {
  I2CAddressMessage& this_ = static_cast<I2CAddressMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL I2CAddressMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) I2CAddressMessage(arena);
}
constexpr auto I2CAddressMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(I2CAddressMessage),
                                            alignof(I2CAddressMessage));
}
constexpr auto I2CAddressMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_I2CAddressMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &I2CAddressMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<I2CAddressMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &I2CAddressMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<I2CAddressMessage>(), &I2CAddressMessage::ByteSizeLong,
              &I2CAddressMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(I2CAddressMessage, _impl_._cached_size_),
          false,
      },
      &I2CAddressMessage::kDescriptorMethods,
      &descriptor_table_AxisMessages_5fsettings_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull I2CAddressMessage_class_data_ =
        I2CAddressMessage::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL I2CAddressMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&I2CAddressMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(I2CAddressMessage_class_data_.tc_table);
  return I2CAddressMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
I2CAddressMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(I2CAddressMessage, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    I2CAddressMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AxisDriver::I2CAddressMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 value = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(I2CAddressMessage, _impl_.value_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(I2CAddressMessage, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 value = 1;
    {PROTOBUF_FIELD_OFFSET(I2CAddressMessage, _impl_.value_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void I2CAddressMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:AxisDriver.I2CAddressMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL I2CAddressMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const I2CAddressMessage& this_ = static_cast<const I2CAddressMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL I2CAddressMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const I2CAddressMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:AxisDriver.I2CAddressMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 value = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_value() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_value(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AxisDriver.I2CAddressMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t I2CAddressMessage::ByteSizeLong(const MessageLite& base) {
  const I2CAddressMessage& this_ = static_cast<const I2CAddressMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t I2CAddressMessage::ByteSizeLong() const {
  const I2CAddressMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:AxisDriver.I2CAddressMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // uint32 value = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_value() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_value());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void I2CAddressMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<I2CAddressMessage*>(&to_msg);
  auto& from = static_cast<const I2CAddressMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AxisDriver.I2CAddressMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_value() != 0) {
      _this->_impl_.value_ = from._impl_.value_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void I2CAddressMessage::CopyFrom(const I2CAddressMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AxisDriver.I2CAddressMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void I2CAddressMessage::InternalSwap(I2CAddressMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.value_, other->_impl_.value_);
}

::google::protobuf::Metadata I2CAddressMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EthernetAddressMessage::_Internal {
 public:
  using HasBits =
      decltype(std::declval<EthernetAddressMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(EthernetAddressMessage, _impl_._has_bits_);
};

EthernetAddressMessage::EthernetAddressMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EthernetAddressMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AxisDriver.EthernetAddressMessage)
}
EthernetAddressMessage::EthernetAddressMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const EthernetAddressMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EthernetAddressMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE EthernetAddressMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void EthernetAddressMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.value_ = {};
}
EthernetAddressMessage::~EthernetAddressMessage() {
  // @@protoc_insertion_point(destructor:AxisDriver.EthernetAddressMessage)
  SharedDtor(*this);
}
inline void EthernetAddressMessage::SharedDtor(MessageLite& self) {
  EthernetAddressMessage& this_ = static_cast<EthernetAddressMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL EthernetAddressMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EthernetAddressMessage(arena);
}
constexpr auto EthernetAddressMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(EthernetAddressMessage),
                                            alignof(EthernetAddressMessage));
}
constexpr auto EthernetAddressMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_EthernetAddressMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &EthernetAddressMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<EthernetAddressMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EthernetAddressMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<EthernetAddressMessage>(), &EthernetAddressMessage::ByteSizeLong,
              &EthernetAddressMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EthernetAddressMessage, _impl_._cached_size_),
          false,
      },
      &EthernetAddressMessage::kDescriptorMethods,
      &descriptor_table_AxisMessages_5fsettings_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull EthernetAddressMessage_class_data_ =
        EthernetAddressMessage::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL EthernetAddressMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&EthernetAddressMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(EthernetAddressMessage_class_data_.tc_table);
  return EthernetAddressMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
EthernetAddressMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EthernetAddressMessage, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    EthernetAddressMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AxisDriver::EthernetAddressMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 value = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(EthernetAddressMessage, _impl_.value_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(EthernetAddressMessage, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 value = 1;
    {PROTOBUF_FIELD_OFFSET(EthernetAddressMessage, _impl_.value_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void EthernetAddressMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:AxisDriver.EthernetAddressMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL EthernetAddressMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const EthernetAddressMessage& this_ = static_cast<const EthernetAddressMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL EthernetAddressMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const EthernetAddressMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:AxisDriver.EthernetAddressMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 value = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_value() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_value(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AxisDriver.EthernetAddressMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t EthernetAddressMessage::ByteSizeLong(const MessageLite& base) {
  const EthernetAddressMessage& this_ = static_cast<const EthernetAddressMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t EthernetAddressMessage::ByteSizeLong() const {
  const EthernetAddressMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:AxisDriver.EthernetAddressMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // uint32 value = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_value() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_value());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void EthernetAddressMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EthernetAddressMessage*>(&to_msg);
  auto& from = static_cast<const EthernetAddressMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AxisDriver.EthernetAddressMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_value() != 0) {
      _this->_impl_.value_ = from._impl_.value_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EthernetAddressMessage::CopyFrom(const EthernetAddressMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AxisDriver.EthernetAddressMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EthernetAddressMessage::InternalSwap(EthernetAddressMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.value_, other->_impl_.value_);
}

::google::protobuf::Metadata EthernetAddressMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class EthernetPortMessage::_Internal {
 public:
  using HasBits =
      decltype(std::declval<EthernetPortMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(EthernetPortMessage, _impl_._has_bits_);
};

EthernetPortMessage::EthernetPortMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EthernetPortMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AxisDriver.EthernetPortMessage)
}
EthernetPortMessage::EthernetPortMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const EthernetPortMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, EthernetPortMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE EthernetPortMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void EthernetPortMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.value_ = {};
}
EthernetPortMessage::~EthernetPortMessage() {
  // @@protoc_insertion_point(destructor:AxisDriver.EthernetPortMessage)
  SharedDtor(*this);
}
inline void EthernetPortMessage::SharedDtor(MessageLite& self) {
  EthernetPortMessage& this_ = static_cast<EthernetPortMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL EthernetPortMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EthernetPortMessage(arena);
}
constexpr auto EthernetPortMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(EthernetPortMessage),
                                            alignof(EthernetPortMessage));
}
constexpr auto EthernetPortMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_EthernetPortMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &EthernetPortMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<EthernetPortMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EthernetPortMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<EthernetPortMessage>(), &EthernetPortMessage::ByteSizeLong,
              &EthernetPortMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EthernetPortMessage, _impl_._cached_size_),
          false,
      },
      &EthernetPortMessage::kDescriptorMethods,
      &descriptor_table_AxisMessages_5fsettings_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull EthernetPortMessage_class_data_ =
        EthernetPortMessage::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL EthernetPortMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&EthernetPortMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(EthernetPortMessage_class_data_.tc_table);
  return EthernetPortMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
EthernetPortMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(EthernetPortMessage, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    EthernetPortMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AxisDriver::EthernetPortMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 value = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(EthernetPortMessage, _impl_.value_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(EthernetPortMessage, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 value = 1;
    {PROTOBUF_FIELD_OFFSET(EthernetPortMessage, _impl_.value_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void EthernetPortMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:AxisDriver.EthernetPortMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL EthernetPortMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const EthernetPortMessage& this_ = static_cast<const EthernetPortMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL EthernetPortMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const EthernetPortMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:AxisDriver.EthernetPortMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 value = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_value() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_value(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AxisDriver.EthernetPortMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t EthernetPortMessage::ByteSizeLong(const MessageLite& base) {
  const EthernetPortMessage& this_ = static_cast<const EthernetPortMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t EthernetPortMessage::ByteSizeLong() const {
  const EthernetPortMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:AxisDriver.EthernetPortMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // uint32 value = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_value() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_value());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void EthernetPortMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<EthernetPortMessage*>(&to_msg);
  auto& from = static_cast<const EthernetPortMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AxisDriver.EthernetPortMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_value() != 0) {
      _this->_impl_.value_ = from._impl_.value_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void EthernetPortMessage::CopyFrom(const EthernetPortMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AxisDriver.EthernetPortMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EthernetPortMessage::InternalSwap(EthernetPortMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.value_, other->_impl_.value_);
}

::google::protobuf::Metadata EthernetPortMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MacAddressMessage::_Internal {
 public:
};

MacAddressMessage::MacAddressMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MacAddressMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AxisDriver.MacAddressMessage)
}
PROTOBUF_NDEBUG_INLINE MacAddressMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::AxisDriver::MacAddressMessage& from_msg)
      : mac_address_{visibility, arena, from.mac_address_},
        _mac_address_cached_byte_size_{0},
        _cached_size_{0} {}

MacAddressMessage::MacAddressMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const MacAddressMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MacAddressMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MacAddressMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:AxisDriver.MacAddressMessage)
}
PROTOBUF_NDEBUG_INLINE MacAddressMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : mac_address_{visibility, arena},
        _mac_address_cached_byte_size_{0},
        _cached_size_{0} {}

inline void MacAddressMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
MacAddressMessage::~MacAddressMessage() {
  // @@protoc_insertion_point(destructor:AxisDriver.MacAddressMessage)
  SharedDtor(*this);
}
inline void MacAddressMessage::SharedDtor(MessageLite& self) {
  MacAddressMessage& this_ = static_cast<MacAddressMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL MacAddressMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) MacAddressMessage(arena);
}
constexpr auto MacAddressMessage::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(MacAddressMessage, _impl_.mac_address_) +
          decltype(MacAddressMessage::_impl_.mac_address_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(MacAddressMessage), alignof(MacAddressMessage), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&MacAddressMessage::PlacementNew_,
                                 sizeof(MacAddressMessage),
                                 alignof(MacAddressMessage));
  }
}
constexpr auto MacAddressMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MacAddressMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &MacAddressMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MacAddressMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MacAddressMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MacAddressMessage>(), &MacAddressMessage::ByteSizeLong,
              &MacAddressMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MacAddressMessage, _impl_._cached_size_),
          false,
      },
      &MacAddressMessage::kDescriptorMethods,
      &descriptor_table_AxisMessages_5fsettings_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull MacAddressMessage_class_data_ =
        MacAddressMessage::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL MacAddressMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MacAddressMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MacAddressMessage_class_data_.tc_table);
  return MacAddressMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
MacAddressMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    MacAddressMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AxisDriver::MacAddressMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated uint32 mac_address = 1;
    {::_pbi::TcParser::FastV32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(MacAddressMessage, _impl_.mac_address_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated uint32 mac_address = 1;
    {PROTOBUF_FIELD_OFFSET(MacAddressMessage, _impl_.mac_address_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void MacAddressMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:AxisDriver.MacAddressMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.mac_address_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL MacAddressMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const MacAddressMessage& this_ = static_cast<const MacAddressMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL MacAddressMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const MacAddressMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:AxisDriver.MacAddressMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated uint32 mac_address = 1;
  {
    int byte_size = this_._impl_._mac_address_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          1, this_._internal_mac_address(), byte_size, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AxisDriver.MacAddressMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MacAddressMessage::ByteSizeLong(const MessageLite& base) {
  const MacAddressMessage& this_ = static_cast<const MacAddressMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t MacAddressMessage::ByteSizeLong() const {
  const MacAddressMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:AxisDriver.MacAddressMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated uint32 mac_address = 1;
    {
      total_size +=
          ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
              this_._internal_mac_address(), 1,
              this_._impl_._mac_address_cached_byte_size_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void MacAddressMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MacAddressMessage*>(&to_msg);
  auto& from = static_cast<const MacAddressMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AxisDriver.MacAddressMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_mac_address()->MergeFrom(from._internal_mac_address());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MacAddressMessage::CopyFrom(const MacAddressMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AxisDriver.MacAddressMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MacAddressMessage::InternalSwap(MacAddressMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.mac_address_.InternalSwap(&other->_impl_.mac_address_);
}

::google::protobuf::Metadata MacAddressMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SaveConfigurationMessage::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SaveConfigurationMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SaveConfigurationMessage, _impl_._has_bits_);
};

SaveConfigurationMessage::SaveConfigurationMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SaveConfigurationMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AxisDriver.SaveConfigurationMessage)
}
SaveConfigurationMessage::SaveConfigurationMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SaveConfigurationMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SaveConfigurationMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE SaveConfigurationMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void SaveConfigurationMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.value_ = {};
}
SaveConfigurationMessage::~SaveConfigurationMessage() {
  // @@protoc_insertion_point(destructor:AxisDriver.SaveConfigurationMessage)
  SharedDtor(*this);
}
inline void SaveConfigurationMessage::SharedDtor(MessageLite& self) {
  SaveConfigurationMessage& this_ = static_cast<SaveConfigurationMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SaveConfigurationMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SaveConfigurationMessage(arena);
}
constexpr auto SaveConfigurationMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SaveConfigurationMessage),
                                            alignof(SaveConfigurationMessage));
}
constexpr auto SaveConfigurationMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SaveConfigurationMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SaveConfigurationMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SaveConfigurationMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SaveConfigurationMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SaveConfigurationMessage>(), &SaveConfigurationMessage::ByteSizeLong,
              &SaveConfigurationMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SaveConfigurationMessage, _impl_._cached_size_),
          false,
      },
      &SaveConfigurationMessage::kDescriptorMethods,
      &descriptor_table_AxisMessages_5fsettings_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SaveConfigurationMessage_class_data_ =
        SaveConfigurationMessage::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL SaveConfigurationMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SaveConfigurationMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SaveConfigurationMessage_class_data_.tc_table);
  return SaveConfigurationMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
SaveConfigurationMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SaveConfigurationMessage, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SaveConfigurationMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AxisDriver::SaveConfigurationMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 value = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SaveConfigurationMessage, _impl_.value_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(SaveConfigurationMessage, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 value = 1;
    {PROTOBUF_FIELD_OFFSET(SaveConfigurationMessage, _impl_.value_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void SaveConfigurationMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:AxisDriver.SaveConfigurationMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SaveConfigurationMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SaveConfigurationMessage& this_ = static_cast<const SaveConfigurationMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SaveConfigurationMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SaveConfigurationMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:AxisDriver.SaveConfigurationMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 value = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_value() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_value(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AxisDriver.SaveConfigurationMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SaveConfigurationMessage::ByteSizeLong(const MessageLite& base) {
  const SaveConfigurationMessage& this_ = static_cast<const SaveConfigurationMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SaveConfigurationMessage::ByteSizeLong() const {
  const SaveConfigurationMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:AxisDriver.SaveConfigurationMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // uint32 value = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_value() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_value());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SaveConfigurationMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SaveConfigurationMessage*>(&to_msg);
  auto& from = static_cast<const SaveConfigurationMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AxisDriver.SaveConfigurationMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_value() != 0) {
      _this->_impl_.value_ = from._impl_.value_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SaveConfigurationMessage::CopyFrom(const SaveConfigurationMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AxisDriver.SaveConfigurationMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SaveConfigurationMessage::InternalSwap(SaveConfigurationMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.value_, other->_impl_.value_);
}

::google::protobuf::Metadata SaveConfigurationMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace AxisDriver
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_AxisMessages_5fsettings_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
