// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AxisMessages_led.proto
// Protobuf C++ Version: 6.30.2

#ifndef AxisMessages_5fled_2eproto_2epb_2eh
#define AxisMessages_5fled_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_AxisMessages_5fled_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_AxisMessages_5fled_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_AxisMessages_5fled_2eproto;
}  // extern "C"
namespace AxisDriver {
class LedColorMessage;
struct LedColorMessageDefaultTypeInternal;
extern LedColorMessageDefaultTypeInternal _LedColorMessage_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull LedColorMessage_class_data_;
class LedStateMessage;
struct LedStateMessageDefaultTypeInternal;
extern LedStateMessageDefaultTypeInternal _LedStateMessage_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull LedStateMessage_class_data_;
}  // namespace AxisDriver
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace AxisDriver {

// ===================================================================


// -------------------------------------------------------------------

class LedStateMessage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:AxisDriver.LedStateMessage) */ {
 public:
  inline LedStateMessage() : LedStateMessage(nullptr) {}
  ~LedStateMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LedStateMessage* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LedStateMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LedStateMessage(::google::protobuf::internal::ConstantInitialized);

  inline LedStateMessage(const LedStateMessage& from) : LedStateMessage(nullptr, from) {}
  inline LedStateMessage(LedStateMessage&& from) noexcept
      : LedStateMessage(nullptr, std::move(from)) {}
  inline LedStateMessage& operator=(const LedStateMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline LedStateMessage& operator=(LedStateMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LedStateMessage& default_instance() {
    return *reinterpret_cast<const LedStateMessage*>(
        &_LedStateMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(LedStateMessage& a, LedStateMessage& b) { a.Swap(&b); }
  inline void Swap(LedStateMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LedStateMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LedStateMessage* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LedStateMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LedStateMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LedStateMessage& from) { LedStateMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LedStateMessage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "AxisDriver.LedStateMessage"; }

 protected:
  explicit LedStateMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  LedStateMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const LedStateMessage& from);
  LedStateMessage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, LedStateMessage&& from) noexcept
      : LedStateMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kValueFieldNumber = 1,
  };
  // uint32 value = 1;
  void clear_value() ;
  ::uint32_t value() const;
  void set_value(::uint32_t value);

  private:
  ::uint32_t _internal_value() const;
  void _internal_set_value(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:AxisDriver.LedStateMessage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const LedStateMessage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t value_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_AxisMessages_5fled_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull LedStateMessage_class_data_;
// -------------------------------------------------------------------

class LedColorMessage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:AxisDriver.LedColorMessage) */ {
 public:
  inline LedColorMessage() : LedColorMessage(nullptr) {}
  ~LedColorMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LedColorMessage* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LedColorMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LedColorMessage(::google::protobuf::internal::ConstantInitialized);

  inline LedColorMessage(const LedColorMessage& from) : LedColorMessage(nullptr, from) {}
  inline LedColorMessage(LedColorMessage&& from) noexcept
      : LedColorMessage(nullptr, std::move(from)) {}
  inline LedColorMessage& operator=(const LedColorMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline LedColorMessage& operator=(LedColorMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LedColorMessage& default_instance() {
    return *reinterpret_cast<const LedColorMessage*>(
        &_LedColorMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(LedColorMessage& a, LedColorMessage& b) { a.Swap(&b); }
  inline void Swap(LedColorMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LedColorMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LedColorMessage* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LedColorMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LedColorMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LedColorMessage& from) { LedColorMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LedColorMessage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "AxisDriver.LedColorMessage"; }

 protected:
  explicit LedColorMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  LedColorMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const LedColorMessage& from);
  LedColorMessage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, LedColorMessage&& from) noexcept
      : LedColorMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLedColorFieldNumber = 1,
  };
  // repeated uint32 led_color = 1;
  int led_color_size() const;
  private:
  int _internal_led_color_size() const;

  public:
  void clear_led_color() ;
  ::uint32_t led_color(int index) const;
  void set_led_color(int index, ::uint32_t value);
  void add_led_color(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& led_color() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_led_color();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_led_color() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_led_color();

  public:
  // @@protoc_insertion_point(class_scope:AxisDriver.LedColorMessage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const LedColorMessage& from_msg);
    ::google::protobuf::RepeatedField<::uint32_t> led_color_;
    ::google::protobuf::internal::CachedSize _led_color_cached_byte_size_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_AxisMessages_5fled_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull LedColorMessage_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// LedStateMessage

// uint32 value = 1;
inline void LedStateMessage::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint32_t LedStateMessage::value() const {
  // @@protoc_insertion_point(field_get:AxisDriver.LedStateMessage.value)
  return _internal_value();
}
inline void LedStateMessage::set_value(::uint32_t value) {
  _internal_set_value(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:AxisDriver.LedStateMessage.value)
}
inline ::uint32_t LedStateMessage::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_;
}
inline void LedStateMessage::_internal_set_value(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_ = value;
}

// -------------------------------------------------------------------

// LedColorMessage

// repeated uint32 led_color = 1;
inline int LedColorMessage::_internal_led_color_size() const {
  return _internal_led_color().size();
}
inline int LedColorMessage::led_color_size() const {
  return _internal_led_color_size();
}
inline void LedColorMessage::clear_led_color() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.led_color_.Clear();
}
inline ::uint32_t LedColorMessage::led_color(int index) const {
  // @@protoc_insertion_point(field_get:AxisDriver.LedColorMessage.led_color)
  return _internal_led_color().Get(index);
}
inline void LedColorMessage::set_led_color(int index, ::uint32_t value) {
  _internal_mutable_led_color()->Set(index, value);
  // @@protoc_insertion_point(field_set:AxisDriver.LedColorMessage.led_color)
}
inline void LedColorMessage::add_led_color(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_led_color()->Add(value);
  // @@protoc_insertion_point(field_add:AxisDriver.LedColorMessage.led_color)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& LedColorMessage::led_color() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:AxisDriver.LedColorMessage.led_color)
  return _internal_led_color();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL LedColorMessage::mutable_led_color()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:AxisDriver.LedColorMessage.led_color)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_led_color();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
LedColorMessage::_internal_led_color() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.led_color_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
LedColorMessage::_internal_mutable_led_color() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.led_color_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace AxisDriver


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // AxisMessages_5fled_2eproto_2epb_2eh
