// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AxisMessages_common.proto
// Protobuf C++ Version: 6.30.2

#include "AxisMessages_common.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace AxisDriver {

inline constexpr Header::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        sync_bytes_{0u},
        message_type_{static_cast< ::AxisDriver::MessageId >(0)},
        body_size_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR Header::Header(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Header_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct HeaderDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeaderDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeaderDefaultTypeInternal() {}
  union {
    Header _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeaderDefaultTypeInternal _Header_default_instance_;

inline constexpr Footer::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        checksum_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR Footer::Footer(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Footer_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FooterDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FooterDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FooterDefaultTypeInternal() {}
  union {
    Footer _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FooterDefaultTypeInternal _Footer_default_instance_;
}  // namespace AxisDriver
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_AxisMessages_5fcommon_2eproto[6];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_AxisMessages_5fcommon_2eproto = nullptr;
const ::uint32_t
    TableStruct_AxisMessages_5fcommon_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::AxisDriver::Header, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::AxisDriver::Header, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AxisDriver::Header, _impl_.sync_bytes_),
        PROTOBUF_FIELD_OFFSET(::AxisDriver::Header, _impl_.message_type_),
        PROTOBUF_FIELD_OFFSET(::AxisDriver::Header, _impl_.body_size_),
        0,
        1,
        2,
        PROTOBUF_FIELD_OFFSET(::AxisDriver::Footer, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::AxisDriver::Footer, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::AxisDriver::Footer, _impl_.checksum_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::AxisDriver::Header)},
        {14, 23, -1, sizeof(::AxisDriver::Footer)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::AxisDriver::_Header_default_instance_._instance,
    &::AxisDriver::_Footer_default_instance_._instance,
};
const char descriptor_table_protodef_AxisMessages_5fcommon_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\031AxisMessages_common.proto\022\nAxisDriver\""
    "\\\n\006Header\022\022\n\nsync_bytes\030\001 \001(\r\022+\n\014message"
    "_type\030\002 \001(\0162\025.AxisDriver.MessageId\022\021\n\tbo"
    "dy_size\030\003 \001(\r\"\032\n\006Footer\022\020\n\010checksum\030\001 \001("
    "\r*c\n\tLedStates\022\007\n\003OFF\020\000\022\017\n\013FLASH_ERROR\020\001"
    "\022\t\n\005ERROR\020\002\022\n\n\006BOOTUP\020\003\022\013\n\007RAINBOW\020\004\022\t\n\005"
    "SOLID\020\005\022\r\n\tMAX_VALUE\020\006*b\n\013MotorStates\022\r\n"
    "\tMOTOR_OFF\020\000\022\014\n\010POSITION\020\001\022\014\n\010VELOCITY\020\002"
    "\022\021\n\rVELOCITY_STEP\020\003\022\013\n\007IDLE_ON\020\004\022\010\n\004HOME"
    "\020\005*K\n\nMotorBrake\022\n\n\006NORMAL\020\000\022\020\n\014FREEWHEE"
    "LING\020\001\022\022\n\016STRONG_BRAKING\020\002\022\013\n\007BRAKING\020\003*"
    "4\n\rHomeDirection\022\r\n\tCLOCKWISE\020\000\022\024\n\020COUNT"
    "ERCLOCKWISE\020\001**\n\014PositionMode\022\014\n\010ABSOLUT"
    "E\020\000\022\014\n\010RELATIVE\020\001*\201\r\n\tMessageId\022\020\n\014GetVe"
    "rsionId\020\000\022\023\n\017SetI2CAddressId\020\001\022\023\n\017GetI2C"
    "AddressId\020\002\022\030\n\024SetEthernetAddressId\020\003\022\030\n"
    "\024GetEthernetAddressId\020\004\022\025\n\021SetEthernetPo"
    "rtId\020\005\022\025\n\021GetEthernetPortId\020\006\022\023\n\017GetMacA"
    "ddressId\020\007\022\027\n\023SaveConfigurationId\020\010\022\021\n\rS"
    "etLedStateId\020\t\022\021\n\rGetLedStateId\020\n\022\021\n\rSet"
    "LedColorId\020\013\022\021\n\rGetLedColorId\020\014\022\026\n\022SetHo"
    "meDirectionId\020\r\022\026\n\022GetHomeDirectionId\020\016\022"
    "\026\n\022SetHomeThresholdId\020\017\022\026\n\022GetHomeThresh"
    "oldId\020\020\022\022\n\016SetHomeSpeedId\020\021\022\022\n\016GetHomeSp"
    "eedId\020\022\022\023\n\017GetHomedStateId\020\023\022\n\n\006HomeId\020\024"
    "\022\023\n\017SetMotorStateId\020\025\022\023\n\017GetMotorStateId"
    "\020\026\022\023\n\017SetMotorBrakeId\020\027\022\023\n\017GetMotorBrake"
    "Id\020\030\022\021\n\rSetMaxSpeedId\020\031\022\021\n\rGetMaxSpeedId"
    "\020\032\022\025\n\021SetAccelerationId\020\033\022\025\n\021GetAccelera"
    "tionId\020\034\022\030\n\024SetCurrentPositionId\020\035\022\030\n\024Ge"
    "tCurrentPositionId\020\036\022\027\n\023SetTargetPositio"
    "nId\020\037\022\027\n\023GetTargetPositionId\020 \022\037\n\033SetRel"
    "ativeTargetPositionId\020!\022\021\n\rSetVelocityId"
    "\020\"\022\021\n\rGetVelocityId\020#\022\031\n\025SetVelocityAndS"
    "tepsId\020$\022\017\n\013StartPathId\020%\022\021\n\rSetHAEnable"
    "Id\020&\022\021\n\rGetHAEnableId\020\'\022\017\n\013SetHAModeId\020("
    "\022\017\n\013GetHAModeId\020)\022\024\n\020SetHAIpAddressId\020*\022"
    "\024\n\020GetHAIpAddressId\020+\022 \n\034SetHAVelocitySw"
    "itchOnSpeedId\020,\022 \n\034GetHAVelocitySwitchOn"
    "SpeedId\020-\022!\n\035SetHAVelocitySwitchOffSpeed"
    "Id\020.\022!\n\035GetHAVelocitySwitchOffSpeedId\020/\022"
    "#\n\037SetHAPositionSwitchOnPositionId\0200\022#\n\037"
    "GetHAPositionSwitchOnPositionId\0201\022$\n Set"
    "HAPositionSwitchOffPositionId\0202\022$\n GetHA"
    "PositionSwitchOffPositionId\0203\022\034\n\030SetHAVe"
    "locitySliderMinId\0204\022\034\n\030GetHAVelocitySlid"
    "erMinId\0205\022\034\n\030SetHAVelocitySliderMaxId\0206\022"
    "\034\n\030GetHAVelocitySliderMaxId\0207\022\034\n\030SetHAPo"
    "sitionSliderMinId\0208\022\034\n\030GetHAPositionSlid"
    "erMinId\0209\022\034\n\030SetHAPositionSliderMaxId\020:\022"
    "\034\n\030GetHAPositionSliderMaxId\020;\022\023\n\017SetHAMq"
    "ttUserId\020<\022\023\n\017GetHAMqttUserId\020=\022\027\n\023SetHA"
    "MqttPasswordId\020>\022\027\n\023GetHAMqttPasswordId\020"
    "\?\022\023\n\017SetHAMqttNameId\020@\022\023\n\017GetHAMqttNameI"
    "d\020A\022\023\n\017SetHAMqttIconId\020B\022\023\n\017GetHAMqttIco"
    "nId\020Cb\006proto3"
};
static ::absl::once_flag descriptor_table_AxisMessages_5fcommon_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_AxisMessages_5fcommon_2eproto = {
    false,
    false,
    2213,
    descriptor_table_protodef_AxisMessages_5fcommon_2eproto,
    "AxisMessages_common.proto",
    &descriptor_table_AxisMessages_5fcommon_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_AxisMessages_5fcommon_2eproto::offsets,
    file_level_enum_descriptors_AxisMessages_5fcommon_2eproto,
    file_level_service_descriptors_AxisMessages_5fcommon_2eproto,
};
namespace AxisDriver {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL LedStates_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_AxisMessages_5fcommon_2eproto);
  return file_level_enum_descriptors_AxisMessages_5fcommon_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t LedStates_internal_data_[] = {
    458752u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL MotorStates_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_AxisMessages_5fcommon_2eproto);
  return file_level_enum_descriptors_AxisMessages_5fcommon_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t MotorStates_internal_data_[] = {
    393216u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL MotorBrake_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_AxisMessages_5fcommon_2eproto);
  return file_level_enum_descriptors_AxisMessages_5fcommon_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t MotorBrake_internal_data_[] = {
    262144u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL HomeDirection_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_AxisMessages_5fcommon_2eproto);
  return file_level_enum_descriptors_AxisMessages_5fcommon_2eproto[3];
}
PROTOBUF_CONSTINIT const uint32_t HomeDirection_internal_data_[] = {
    131072u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PositionMode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_AxisMessages_5fcommon_2eproto);
  return file_level_enum_descriptors_AxisMessages_5fcommon_2eproto[4];
}
PROTOBUF_CONSTINIT const uint32_t PositionMode_internal_data_[] = {
    131072u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL MessageId_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_AxisMessages_5fcommon_2eproto);
  return file_level_enum_descriptors_AxisMessages_5fcommon_2eproto[5];
}
PROTOBUF_CONSTINIT const uint32_t MessageId_internal_data_[] = {
    4456448u, 0u, };
// ===================================================================

class Header::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Header>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Header, _impl_._has_bits_);
};

Header::Header(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Header_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AxisDriver.Header)
}
Header::Header(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Header& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Header_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Header::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Header::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, sync_bytes_),
           0,
           offsetof(Impl_, body_size_) -
               offsetof(Impl_, sync_bytes_) +
               sizeof(Impl_::body_size_));
}
Header::~Header() {
  // @@protoc_insertion_point(destructor:AxisDriver.Header)
  SharedDtor(*this);
}
inline void Header::SharedDtor(MessageLite& self) {
  Header& this_ = static_cast<Header&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Header::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Header(arena);
}
constexpr auto Header::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Header),
                                            alignof(Header));
}
constexpr auto Header::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Header_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Header::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Header>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Header::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Header>(), &Header::ByteSizeLong,
              &Header::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Header, _impl_._cached_size_),
          false,
      },
      &Header::kDescriptorMethods,
      &descriptor_table_AxisMessages_5fcommon_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Header_class_data_ =
        Header::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL Header::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Header_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Header_class_data_.tc_table);
  return Header_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
Header::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Header, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Header_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AxisDriver::Header>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 sync_bytes = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Header, _impl_.sync_bytes_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(Header, _impl_.sync_bytes_)}},
    // .AxisDriver.MessageId message_type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Header, _impl_.message_type_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(Header, _impl_.message_type_)}},
    // uint32 body_size = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Header, _impl_.body_size_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(Header, _impl_.body_size_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 sync_bytes = 1;
    {PROTOBUF_FIELD_OFFSET(Header, _impl_.sync_bytes_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // .AxisDriver.MessageId message_type = 2;
    {PROTOBUF_FIELD_OFFSET(Header, _impl_.message_type_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // uint32 body_size = 3;
    {PROTOBUF_FIELD_OFFSET(Header, _impl_.body_size_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Header::Clear() {
// @@protoc_insertion_point(message_clear_start:AxisDriver.Header)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    ::memset(&_impl_.sync_bytes_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.body_size_) -
        reinterpret_cast<char*>(&_impl_.sync_bytes_)) + sizeof(_impl_.body_size_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Header::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Header& this_ = static_cast<const Header&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Header::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Header& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:AxisDriver.Header)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 sync_bytes = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_sync_bytes() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_sync_bytes(), target);
    }
  }

  // .AxisDriver.MessageId message_type = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_message_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          2, this_._internal_message_type(), target);
    }
  }

  // uint32 body_size = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_body_size() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          3, this_._internal_body_size(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AxisDriver.Header)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Header::ByteSizeLong(const MessageLite& base) {
  const Header& this_ = static_cast<const Header&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Header::ByteSizeLong() const {
  const Header& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:AxisDriver.Header)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // uint32 sync_bytes = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_sync_bytes() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_sync_bytes());
      }
    }
    // .AxisDriver.MessageId message_type = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_message_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_message_type());
      }
    }
    // uint32 body_size = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_body_size() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_body_size());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Header::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Header*>(&to_msg);
  auto& from = static_cast<const Header&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AxisDriver.Header)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (from._internal_sync_bytes() != 0) {
        _this->_impl_.sync_bytes_ = from._impl_.sync_bytes_;
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_message_type() != 0) {
        _this->_impl_.message_type_ = from._impl_.message_type_;
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_body_size() != 0) {
        _this->_impl_.body_size_ = from._impl_.body_size_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Header::CopyFrom(const Header& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AxisDriver.Header)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Header::InternalSwap(Header* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Header, _impl_.body_size_)
      + sizeof(Header::_impl_.body_size_)
      - PROTOBUF_FIELD_OFFSET(Header, _impl_.sync_bytes_)>(
          reinterpret_cast<char*>(&_impl_.sync_bytes_),
          reinterpret_cast<char*>(&other->_impl_.sync_bytes_));
}

::google::protobuf::Metadata Header::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Footer::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Footer>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Footer, _impl_._has_bits_);
};

Footer::Footer(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Footer_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AxisDriver.Footer)
}
Footer::Footer(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Footer& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Footer_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Footer::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Footer::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.checksum_ = {};
}
Footer::~Footer() {
  // @@protoc_insertion_point(destructor:AxisDriver.Footer)
  SharedDtor(*this);
}
inline void Footer::SharedDtor(MessageLite& self) {
  Footer& this_ = static_cast<Footer&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Footer::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Footer(arena);
}
constexpr auto Footer::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Footer),
                                            alignof(Footer));
}
constexpr auto Footer::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Footer_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Footer::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Footer>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Footer::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Footer>(), &Footer::ByteSizeLong,
              &Footer::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Footer, _impl_._cached_size_),
          false,
      },
      &Footer::kDescriptorMethods,
      &descriptor_table_AxisMessages_5fcommon_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Footer_class_data_ =
        Footer::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL Footer::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Footer_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Footer_class_data_.tc_table);
  return Footer_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
Footer::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Footer, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Footer_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AxisDriver::Footer>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 checksum = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Footer, _impl_.checksum_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(Footer, _impl_.checksum_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 checksum = 1;
    {PROTOBUF_FIELD_OFFSET(Footer, _impl_.checksum_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Footer::Clear() {
// @@protoc_insertion_point(message_clear_start:AxisDriver.Footer)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.checksum_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Footer::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Footer& this_ = static_cast<const Footer&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Footer::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Footer& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:AxisDriver.Footer)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 checksum = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_checksum() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_checksum(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AxisDriver.Footer)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Footer::ByteSizeLong(const MessageLite& base) {
  const Footer& this_ = static_cast<const Footer&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Footer::ByteSizeLong() const {
  const Footer& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:AxisDriver.Footer)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // uint32 checksum = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_checksum() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_checksum());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Footer::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Footer*>(&to_msg);
  auto& from = static_cast<const Footer&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AxisDriver.Footer)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_checksum() != 0) {
      _this->_impl_.checksum_ = from._impl_.checksum_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Footer::CopyFrom(const Footer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AxisDriver.Footer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Footer::InternalSwap(Footer* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.checksum_, other->_impl_.checksum_);
}

::google::protobuf::Metadata Footer::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace AxisDriver
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_AxisMessages_5fcommon_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
